stages:
  data_ingestion:
    cmd: python src/Classification/pipeline/stage_01_data_ingestion.py
    deps:
      - src/Classification/pipeline/stage_01_data_ingestion.py
      - config/config.yaml
    outs:
      - artifacts/data_ingestion/Chest-CT-Scan-data

  prepare_base_model:
    cmd: python src/Classification/pipeline/stage_02_prepare_base_model.py
    deps:
      - src/Classification/pipeline/stage_02_prepare_base_model.py
      - config/config.yaml
    params:
      - IMAGE_SIZE
      - INCLUDE_TOP
      - CLASSES
      - WEIGHTS
      - LEARNING_RATE
    outs:
      - artifacts/prepare_base_model

  model_training:
    cmd: python src/Classification/pipeline/stage_03_model_trainer.py
    deps:
      - src/Classification/pipeline/stage_03_model_trainer.py
      - config/config.yaml
      - artifacts/prepare_base_model
      - artifacts/data_ingestion/Chest-CT-Scan-data
    params:
      - EPOCHS
      - BATCH_SIZE
      - IMAGE_SIZE
      - AUGMENTATION
    outs:
      - artifacts/training/model.h5

  model_evaluation:
    cmd: python src/Classification/pipeline/stage_04_model_evaluation_with_mlflow.py
    deps:
      - src/Classification/pipeline/stage_04_model_evaluation_with_mlflow.py
      - config/config.yaml
      - artifacts/training/model.h5
      - artifacts/data_ingestion/Chest-CT-Scan-data
    params:
      - BATCH_SIZE
      - IMAGE_SIZE
    metrics:
      - scores.json :
          cache: false
